dist: trusty
language: elixir
addons:
  postgresql: '9.5'
services:
  - postgresql
elixir:
  - 1.4.2
otp_release:
  - 19.1
# Maybe need some nvm goodness here as well with an npm i
before_script:
  - psql -c 'create database just_ci_test;' -U postgres
  - psql -c 'ALTER USER postgres WITH PASSWORD \'postgres\';' -U postgres
  - mix do ecto.create, ecto.migrate
